# Web Search API Keys (choose one or both)
TAVILY_API_KEY="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"     # Get your key at https://tavily.com
PERPLEXITY_API_KEY="pplx-xxxxx"  # Get your key at https://www.perplexity.ai
GOOGLE_API_KEY="AIzaSyC1FCC7z9RZ2d7-jhihIMSyrhY913E_7tk"

# Wait 60 seconds before connecting using these details, or login to https://console.neo4j.io to validate the Aura Instance is available
NEO4J_URI="neo4j+s://e4035e9b.databases.neo4j.io"
NEO4J_USERNAME="neo4j"
NEO4J_PASSWORD="sQGWyNiJAVgb4IpbBTn8lzbJ-QjzqosSq2kCfPf3eF4"
AURA_INSTANCEID="e4035e9b"
AURA_INSTANCENAME="Instance01"